//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPITareas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int Id { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string descripcion { get; set; }
        public bool ind_finalizada { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public string usuario { get; set; }
    }
}
